create table if not exists competition (
    budget integer,
    date date,
    num_of_participants integer,
    id bigint generated by default as identity,
    referee_id bigint,
    stadium_id bigint,
    user_id bigint,
    name varchar(255),
    place varchar(255),
    type varchar(255),
    primary key (id));

create table if not exists referee (
    age integer,
    salary integer,
    id bigint generated by default as identity,
    full_name varchar(255),
    primary key (id));

create table if not exists sportsman (
    age integer,
    salary integer,
    competition_id bigint,
    id bigint generated by default as identity,
    full_name varchar(255),
    primary key (id));

create table if not exists stadium (
    capacity integer,
    id bigint generated by default as identity,
    address varchar(255),
    name varchar(255),
    primary key (id));

create table if not exists user_role (
    user_id bigint not null,
    roles varchar(255) check (roles in ('ROLE_ADMIN','ROLE_USER')));

create table if not exists users (
    id bigint generated by default as identity,
    password varchar(255),
    username varchar(255),
    primary key (id));

alter table if exists competition add constraint FKlw55agtwp4su7n6ssbbmim7pe foreign key (referee_id) references referee;
alter table if exists competition add constraint FKnfsbl9ybi0p9vkiwgm099etc3 foreign key (stadium_id) references stadium;
alter table if exists competition add constraint FKgyr4whp7gj44n27eb4irravua foreign key (user_id) references users;
alter table if exists sportsman add constraint FKc6tfbyt1w1akn5k8x2q4cqqp6 foreign key (competition_id) references competition;
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;